version: "2"
linters:
  enable:
    - contextcheck
    - gocritic
    - gosec
    - misspell
    - unconvert
  settings:
    gosec:
      excludes:
        - G204
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/NVIDIA/k8s-kata-manager
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
